### PR TITLE
Added dc:creator

### PR DESCRIPTION
**Pull request by hauschke**
**[VIVO-Ontology GitHub issue](https://github.com/vivo-ontologies/vivo-ontology/issues)**: https://github.com/vivo-ontologies/vivo-ontology/issues/58

# What does this pull request do?
This PR adds information about the creator of the VIVO Ontology to the vivo.owl.

# What's new?
The namespace dc="http://purl.org/dc/elements/1.1/" and the information about the creator of the VIVO Ontology to the vivo.owl.

# Interested parties
@vivo-ontologies/team-members

### CODE REVIEW

**Review by chenejac — COMMENTED** [review]
If we are introducing here dc namespace, should we consider using other dc elements (description, title, subject, etc.)?

**Comment by StroemPhi** [comment]
Sorry for popping in from the side line. I just wanted to let you know that dcterms is encourraged over dc elements. It might only be necessary to use dc elemtns in those case where there is no IRI as object available and DC Terms actually expects one instead of a String, but I believe such a hard restriction is not enforced. All OBO ontologies are in the middle of replacing dce with dcterms.

**Comment by hauschke** [comment]
@chenejac 
> If we are introducing here dc namespace, should we consider using other dc elements (description, title, subject, etc.)?

Yes, we will use further elements. In accordance with a decision from the last Ontology we just divide this on separate PRs to make this easier to review. A PR for e.g. dc:description is here: https://github.com/vivo-ontologies/vivo-ontology/pull/66

@StroemPhi
>  I just wanted to let you know that dcterms is encourraged over dc elements. It might only be necessary to use dc elemtns in those case where there is no IRI as object available and DC Terms actually expects one instead of a String, but I believe such a hard restriction is not enforced. All OBO ontologies are in the middle of replacing dce with dcterms.

Thanks! Is this in aligment with the TS recommendations (CC @SArndt-TIB)?

**Comment by SArndt-TIB** [comment]
@hauschke Yes, we also recommend http://purl.org/dc/terms/creator as property and providing IRIs for the creators.

**Comment by StroemPhi** [comment]
context taken from https://www.dublincore.org/specifications/dublin-core/dcmi-terms/:
"http://purl.org/dc/terms/ The /terms/ namespace was originally created in 2001 for identifying new terms coined outside of the original fifteen-element Dublin Core. In 2008, in the context of defining formal semantic constraints for DCMI metadata terms in support of RDF applications, the original fifteen elements themselves were mirrored in the /terms/ namespace. As a result, there exists both a dc:date (http://purl.org/dc/elements/1.1/date) with no formal range and a corresponding dcterms:date (http://purl.org/dc/terms/date) with a formal range of "literal". While these distinctions are significant for creators of RDF applications, most users can safely treat the fifteen parallel properties as equivalent. The most useful properties and classes of DCMI Metadata Terms have now been published as ISO 15836-2:2019 [[ISO 15836-2:2019](https://www.iso.org/standard/71341.html)]. While the /elements/1.1/ namespace will be supported indefinitely, DCMI gently encourages use of the /terms/ namespace."

**Comment by hauschke** [comment]
In https://wiki.lyrasis.org/display/VIVO/2024-07-03+Ontology+Interest+Group+Call @annakasprzik noted: "Should be defined as an entity.", @StroemPhi and  @SArndt-TIB are on the same page as far as I know.

I think we have no entity that we could link to. We could create one and then provide a label for it, but I think this is uncessarily complex. Opionions?

**Review by chenejac — APPROVED** [review]
Looks good to me.

**Pull request merged**
